name: work2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.7.22=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.1.0=he5830b7_0
  - libgomp=13.1.0=he5830b7_0
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.43.0=h2797004_0
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4=hcb278e6_0
  - openssl=3.1.2=hd590300_0
  - python=3.9.17=h0755675_0_cpython
  - readline=8.2=h8228510_1
  - tk=8.6.12=h27826a3_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
    - absl-py==1.4.0
    - anyio==4.0.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.4.0
    - astunparse==1.6.3
    - async-lru==2.0.4
    - attrs==23.1.0
    - babel==2.12.1
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - bleach==6.0.0
    - cachetools==5.3.1
    - certifi==2023.7.22
    - cffi==1.15.1
    - chardet==4.0.0
    - charset-normalizer==3.2.0
    - clarabel==0.6.0
    - click==8.1.7
    - comm==0.1.4
    - contextlib2==21.6.0
    - contourpy==1.1.0
    - cvxopt==1.3.2
    - cvxpy==1.4.1
    - cycler==0.11.0
    - debugpy==1.8.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.7
    - ecos==2.0.12
    - exceptiongroup==1.1.3
    - executing==1.2.0
    - fastjsonschema==2.18.0
    - filelock==3.0.12
    - flatbuffers==23.5.26
    - fonttools==4.42.1
    - fqdn==1.5.1
    - gast==0.4.0
    - gdown==4.7.1
    - google-auth==2.22.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.57.0
    - h5py==3.9.0
    - htcondor==23.0.2
    - idna==2.10
    - imageio==2.33.0
    - importlib-metadata==6.8.0
    - importlib-resources==6.0.1
    - ipykernel==6.25.2
    - ipython==8.15.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.1.1
    - isoduration==20.11.0
    - jax==0.4.20
    - jaxlib==0.4.20+cuda11.cudnn86
    - jedi==0.19.0
    - jinja2==3.1.2
    - joblib==1.3.2
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.19.0
    - jsonschema-specifications==2023.7.1
    - jupyter==1.0.0
    - jupyter-client==8.3.1
    - jupyter-console==6.6.3
    - jupyter-core==5.3.1
    - jupyter-events==0.7.0
    - jupyter-lsp==2.2.0
    - jupyter-server==2.7.3
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.0.5
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.25.0
    - jupyterlab-widgets==3.0.9
    - keras==2.11.0
    - kiwisolver==1.4.5
    - kpla==1.0
    - latent-shift-adaptation==0.1.0
    - lazy-loader==0.3
    - libclang==16.0.6
    - littleutils==0.2.2
    - llvmlite==0.40.1
    - markdown==3.4.4
    - markupsafe==2.1.3
    - matplotlib==3.7.2
    - matplotlib-inline==0.1.6
    - mimic-experiments==0.0
    - mistune==3.0.1
    - ml-collections==0.1.1
    - ml-dtypes==0.2.0
    - multiprocess==0.70.15
    - nbclient==0.8.0
    - nbconvert==7.8.0
    - nbformat==5.9.2
    - nest-asyncio==1.5.7
    - networkx==3.2.1
    - notebook==7.0.3
    - notebook-shim==0.2.3
    - numba==0.57.1
    - numpy==1.24.3
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cuda-cupti-cu11==11.8.87
    - nvidia-cuda-nvcc-cu11==11.8.89
    - nvidia-cuda-nvrtc-cu11==11.8.89
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cudnn-cu11==8.9.4.25
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cusolver-cu11==11.4.1.48
    - nvidia-cusparse-cu11==11.7.5.86
    - nvidia-nccl-cu11==2.19.3
    - oauthlib==3.2.2
    - ogb==1.3.6
    - opt-einsum==3.3.0
    - osqp==0.6.3
    - outdated==0.2.2
    - overrides==7.4.0
    - packaging==23.1
    - pandas==2.0.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - patsy==0.5.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==10.0.0
    - pip==23.3.1
    - platformdirs==3.10.0
    - prometheus-client==0.17.1
    - prompt-toolkit==3.0.39
    - protobuf==3.19.6
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pybind11==2.11.1
    - pycparser==2.21
    - pygments==2.16.1
    - pyparsing==3.0.9
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - python-utils==3.7.0
    - pytz==2023.3
    - pyyaml==6.0.1
    - pyzmq==25.1.1
    - qdldl==0.1.7.post0
    - qtconsole==5.4.4
    - qtpy==2.4.0
    - referencing==0.30.2
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.10.3
    - rsa==4.9
    - scikit-image==0.22.0
    - scikit-learn==1.3.0
    - scipy==1.11.2
    - scs==3.2.4.post1
    - seaborn==0.13.0
    - send2trash==1.8.2
    - setuptools==68.2.2
    - six==1.16.0
    - sniffio==1.3.0
    - soupsieve==2.5
    - stack-data==0.6.2
    - statsmodels==0.14.0
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.11.0
    - tensorflow-estimator==2.11.0
    - tensorflow-io-gcs-filesystem==0.28.0
    - termcolor==2.3.0
    - terminado==0.17.1
    - threadpoolctl==3.2.0
    - tifffile==2023.9.26
    - tinycss2==1.2.1
    - tomli==2.0.1
    - torch==1.13.1+cu116
    - torchaudio==0.13.1+cu116
    - torchvision==0.14.1+cu116
    - tornado==6.3.3
    - tqdm==4.66.1
    - traitlets==5.10.0
    - typing-extensions==4.5.0
    - tzdata==2023.3
    - uri-template==1.3.0
    - urllib3==1.26.16
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.3
    - werkzeug==2.3.7
    - widgetsnbextension==4.0.9
    - wilds==2.0.0
    - wrapt==1.15.0
    - zipp==3.16.2
prefix: /home/kt14/miniconda3/envs/work2

